
# After that, you can edit ~/.aerospace.toml to your liking

# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']


# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
ctrl-shift-cmd-z = 'layout tiles horizontal vertical'
ctrl-shift-cmd-x = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-shift-cmd-a = 'focus left'
ctrl-shift-cmd-s = 'focus down'
ctrl-shift-cmd-d = 'focus up'
ctrl-shift-cmd-f = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-shift-cmd-alt-a = 'move left'
ctrl-shift-cmd-alt-s = 'move down'
ctrl-shift-cmd-alt-d = 'move up'
ctrl-shift-cmd-alt-f = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-cmd-shift-2 = 'resize smart -50'
ctrl-cmd-shift-1 = 'resize smart +50'

ctrl-shift-cmd-c = 'fullscreen'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
# ctrl-shift-cmd-1 = 'workspace 1'
# ctrl-shift-cmd-2 = 'workspace 2'
# ctrl-shift-cmd-3 = 'workspace 3'
# ctrl-shift-cmd-4 = 'workspace 4'
# ctrl-shift-cmd-5 = 'workspace 5'
# ctrl-shift-cmd-6 = 'workspace 6'
# ctrl-shift-cmd-7 = 'workspace 7'
# ctrl-shift-cmd-8 = 'workspace 8'
# ctrl-shift-cmd-9 = 'workspace 9'
# ctrl-shift-cmd-a = 'workspace A'
ctrl-shift-cmd-b = 'workspace B'
# ctrl-shift-cmd-c = 'workspace C'
# ctrl-shift-cmd-d = 'workspace D'
ctrl-shift-cmd-e = 'workspace E'
# ctrl-shift-cmd-f = 'workspace F'
# ctrl-shift-cmd-g = 'workspace G'
# ctrl-shift-cmd-h = 'workspace H'
# ctrl-shift-cmd-i = 'workspace I'
# ctrl-shift-cmd-j = 'workspace J'
# ctrl-shift-cmd-k = 'workspace K'
# ctrl-shift-cmd-l = 'workspace L'
ctrl-shift-cmd-m = 'workspace M'
ctrl-shift-cmd-n = 'workspace N'
# ctrl-shift-cmd-o = 'workspace O'
# ctrl-shift-cmd-p = 'workspace P'
ctrl-shift-cmd-q = 'workspace Q'
ctrl-shift-cmd-r = 'workspace R'
# ctrl-shift-cmd-s = 'workspace S'
ctrl-shift-cmd-t = 'workspace T'
# ctrl-shift-cmd-u = 'workspace U'
ctrl-shift-cmd-v = 'workspace V'
ctrl-shift-cmd-w = 'workspace W'
# ctrl-shift-cmd-x = 'workspace X'
ctrl-shift-cmd-y = 'workspace Y'
# ctrl-shift-cmd-z = 'workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
# ctrl-shift-cmd-alt-1 = 'move-node-to-workspace 1'
# ctrl-shift-cmd-alt-2 = 'move-node-to-workspace 2'
# ctrl-shift-cmd-alt-3 = 'move-node-to-workspace 3'
# ctrl-shift-cmd-alt-4 = 'move-node-to-workspace 4'
# ctrl-shift-cmd-alt-5 = 'move-node-to-workspace 5'
# ctrl-shift-cmd-alt-6 = 'move-node-to-workspace 6'
# ctrl-shift-cmd-alt-7 = 'move-node-to-workspace 7'
# ctrl-shift-cmd-alt-8 = 'move-node-to-workspace 8'
# ctrl-shift-cmd-alt-9 = 'move-node-to-workspace 9'
# ctrl-shift-cmd-alt-a = 'move-node-to-workspace A'
ctrl-shift-cmd-alt-b = 'move-node-to-workspace B'
# ctrl-shift-cmd-alt-c = 'move-node-to-workspace C'
# ctrl-shift-cmd-alt-d = 'move-node-to-workspace D'
ctrl-shift-cmd-alt-e = 'move-node-to-workspace E'
# ctrl-shift-cmd-alt-f = 'move-node-to-workspace F'
# ctrl-shift-cmd-alt-g = 'move-node-to-workspace G'
# ctrl-shift-cmd-alt-h = 'move-node-to-workspace H'
# ctrl-shift-cmd-alt-i = 'move-node-to-workspace I'
# ctrl-shift-cmd-alt-j = 'move-node-to-workspace J'
# ctrl-shift-cmd-alt-k = 'move-node-to-workspace K'
# ctrl-shift-cmd-alt-l = 'move-node-to-workspace L'
ctrl-shift-cmd-alt-m = 'move-node-to-workspace M'
ctrl-shift-cmd-alt-n = 'move-node-to-workspace N'
# ctrl-shift-cmd-alt-o = 'move-node-to-workspace O'
# ctrl-shift-cmd-alt-p = 'move-node-to-workspace P'
ctrl-shift-cmd-alt-q = 'move-node-to-workspace Q'
ctrl-shift-cmd-alt-r = 'move-node-to-workspace R'
# ctrl-shift-cmd-alt-s = 'move-node-to-workspace S'
ctrl-shift-cmd-alt-t = 'move-node-to-workspace T'
# ctrl-shift-cmd-alt-u = 'move-node-to-workspace U'
ctrl-shift-cmd-alt-v = 'move-node-to-workspace V'
ctrl-shift-alt-cmd-w = 'move-node-to-workspace W'
# ctrl-shift-cmd-cmd-x = 'move-node-to-workspace X'
ctrl-shift-cmd-alt-y = 'move-node-to-workspace Y'
# ctrl-shift-cmd-cmd-z = 'move-node-to-workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
ctrl-shift-cmd-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
ctrl-shift-cmd-alt-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
ctrl-shift-cmd-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

ctrl-cmd-shift-a = ['join-with left', 'mode main']
ctrl-cmd-shift-s = ['join-with down', 'mode main']
ctrl-cmd-shift-d = ['join-with up', 'mode main']
ctrl-cmd-shift-f = ['join-with right', 'mode main']

# [[on-window-detected]]
# if.app-id = 'com.apple.mail'
# run = "move-node-to-workspace N"
[[on-window-detected]]
if.app-id = 'com.apple.QuickTimePlayerX'
run = ['layout tiling', 'move-node-to-workspace Q']
[[on-window-detected]]
if.app-id = 'org.videolan.vlc'
run = ['layout tiling', 'move-node-to-workspace Q']
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = ['layout tiling', 'move-node-to-workspace B']
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['layout tiling', 'move-node-to-workspace M']
[[on-window-detected]]
if.app-id = 'com.tdesktop.Telegram'
run = ['layout tiling', 'move-node-to-workspace M']
[[on-window-detected]]
if.app-id = 'com.tinyapp.TablePlus'
run = ['layout tiling', 'move-node-to-workspace V']
[[on-window-detected]]
if.app-id = 'com.usebruno.app'
run = ['layout tiling', 'move-node-to-workspace N']
