[window]
padding = { x = 8, y = 26 }
position =  { x = 304, y = 248 }
# position =  { x = 202, y = 80 }
dimensions = { columns = 128, lines = 36}
# dimensions = { columns = 112, lines = 36}
# dynamic_padding = true
decorations = "Transparent"
opacity = 0.4
blur= true
startup_mode = "Windowed"

[colors.primary]
background="#000000"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }, 
  { key = "K", mods = "Control | Shift", action = "ToggleViMode"},
  { key = "H", mods = "Control | Shift", action = "HideOtherApplications"},
  { key = "L", mods = "Control | Shift", action = "CreateNewWindow"},
  { key = "T", mods = "Control | Shift", action = "ToggleMaximized"}
]

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
# bold = { family = "Hack Nerd Font", style = "Bold" }
# italic = { family = "Hack Nerd Font", style = "Italic" }
size = 16
